### ISSUE TITLE
not compatible angular 4?

### ISSUE THREAD

**Issue by maromp** [Ants24/angular2-datatable-pagination#3]
When compile with angular-cli Angular v4:

ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are
not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol
NgModule in......

**Comment by Lokomojo** [comment]
I forked and fixed this: https://github.com/CasperTech/angular2-datatable-pagination

**Comment by NeodymiumMan** [comment]
My project is pulling from npm, any chance this fix can be applied to the published version?

**Comment by Lokomojo** [comment]
Until this issue is resolved by the maintainer, you can:

npm uninstall angular2-datatable-pagination --save
npm install https://github.com/CasperTech/angular2-datatable-pagination.git --save

**Comment by NeodymiumMan** [comment]
Fantastic, thanks for the update!

**Comment by yogeshfcc** [comment]
@TomMettam I am pointing my dependency to your forked version

`npm install https://github.com/CasperTech/angular2-datatable-pagination.git --save`

it was working fine in Angular 4, but when migrated the project to Angular 5 I am getting following error:

```
WARNING in ./node_modules/angular2-datatable-pagination/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\projectangular5\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\projectangular5\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\projectangular5\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\projectangular5\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\projectangular5\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\projectangular5\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\projectangular5\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
 @ ./node_modules/angular2-datatable-pagination/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/angular2-datatable-pagination/lib/NG2DataTableModule.js
 @ ./node_modules/angular2-datatable-pagination/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in ./node_modules/angular2-datatable-pagination/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\projectangular5\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\projectangular5\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\projectangular5\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\projectangular5\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\projectangular5\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\projectangular5\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\projectangular5\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
 @ ./node_modules/angular2-datatable-pagination/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/angular2-datatable-pagination/lib/NG2DataTableModule.js
 @ ./node_modules/angular2-datatable-pagination/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

Any suggestions on how to fix this?

**Comment by robsoncloud** [comment]
I'm facing the same problem as @yogeshfcc 
Any news?

**Comment by yogeshfcc** [comment]
@robk9e Sorry for the late response.

I have fixed this. Please follow below steps to fix the issue

```
npm uninstall angular2-datatable-pagination --save
npm install https://github.com/yogeshfcc/angular2-datatable-pagination.git --save
```

Let me know if you face any further issues.

**Comment by vsrp** [comment]
yogesh- I am getting the following error when I ran this command
**npm install https://github.com/yogeshfcc/angular2-datatable-pagination.git --save**

Any suggestion please ? Thanks!

**Log Details**

23 verbose resolveHead git+https://github.com/yogeshfcc/angular2-datatable-pagination.git original treeish: master
24 info git [ 'rev-list', '-n1', 'master' ]
25 error git rev-list -n1 master: fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
25 error git rev-list -n1 master: Use '--' to separate paths from revisions, like this:
25 error git rev-list -n1 master: 'git <command> [<revision>...] -- [<file>...]'
26 silly fetchPackageMetaData Error: Command failed: git -c core.longpaths=true rev-list -n1 master
26 silly fetchPackageMetaData fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
26 silly fetchPackageMetaData Use '--' to separate paths from revisions, like this:
26 silly fetchPackageMetaData 'git <command> [<revision>...] -- [<file>...]'
26 silly fetchPackageMetaData
26 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:206:12)
26 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
26 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
26 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:877:16)
26 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
26 silly fetchPackageMetaData  error for https://github.com/yogeshfcc/angular2-datatable-pagination.git { Error: Command failed: git -c core.longpaths=true rev-list -n1 master
26 silly fetchPackageMetaData fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
26 silly fetchPackageMetaData Use '--' to separate paths from revisions, like this:
26 silly fetchPackageMetaData 'git <command> [<revision>...] -- [<file>...]'
26 silly fetchPackageMetaData
26 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:206:12)
26 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
26 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
26 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:877:16)
26 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
26 silly fetchPackageMetaData   killed: false,
26 silly fetchPackageMetaData   code: 128,
26 silly fetchPackageMetaData   signal: null,
26 silly fetchPackageMetaData   cmd: 'git -c core.longpaths=true rev-list -n1 master' }
27 silly rollbackFailedOptional Starting
28 silly rollbackFailedOptional Finishing
29 silly runTopLevelLifecycles Finishing

**Comment by yogeshfcc** [comment]
Hello @vsrp ,

I was able to run the 

`npm install https://github.com/yogeshfcc/angular2-datatable-pagination.git --save`

command without any issues. Please try deleting the package.lock.json and do clean 

`npm install` 

and try installing the `angular2-datatable-pagination` dependency. Hopefully that should resolve your issue.

**Comment by romykundal** [comment]
I am working on angular 4. I got error about datatable don't support for the same. 

I came here and i unnstall git+https://github.com/singhdeepme/angular2-datatable-pagination.git
and install and npm install https://github.com/CasperTech/angular2-datatable-pagination.git --save this,

I got solved my error and resume on my project.

Thank to @TomMettam

**Comment by Lokomojo** [comment]
For interested folks, I ended up using https://github.com/swimlane/ngx-datatable
