### ISSUE TITLE
Not working when migrated to Angular 5

### ISSUE THREAD

**Issue by yogeshfcc** [Ants24/angular2-datatable-pagination#7]
@Ants24 
Following is the error I am getting:-

```
WARNING in ./node_modules/angular2-datatable-pagination/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\projectangular5\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\projectangular5\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\projectangular5\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\projectangular5\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\projectangular5\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\projectangular5\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\projectangular5\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
 @ ./node_modules/angular2-datatable-pagination/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/angular2-datatable-pagination/lib/NG2DataTableModule.js
 @ ./node_modules/angular2-datatable-pagination/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in ./node_modules/angular2-datatable-pagination/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\projectangular5\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\projectangular5\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\projectangular5\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\projectangular5\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\projectangular5\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\projectangular5\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\projectangular5\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
 @ ./node_modules/angular2-datatable-pagination/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/angular2-datatable-pagination/lib/NG2DataTableModule.js
 @ ./node_modules/angular2-datatable-pagination/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

**Comment by phi293** [comment]
+1, is there any chance that it will be working for Angular 5?
